deployment:
  - name: pink
    replicas: 1
    color: pink
    weight: 100
  - name: red
    replicas: 1
    color: red
    weight: 100
  - name: purple
    replicas: 1
    color: purple
    weight: 100