apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Chart.Name }}-html'
  annotations:
    configmap.hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
immutable: false
data:
{{ (.Files.Glob "html/*").AsConfig | indent 2 }}